Update github-actions.md
This step was missing from the optimize docker build using cache, without it the build fails with the following error message

```
Error: buildx failed with: ERROR: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```