Pip fails due to MTU mismatch
When building a container, pip fails if MTU of the host external network is less than 1500. It throws the following error:

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/flask
ERROR: Could not find a version that satisfies the requirement Flask (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for Flask (from -r requirements.txt (line 1))
The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 1

To fix it, the MTU of the docker bridge network should either be less than or equal to that of the host.