fix(yaml): Avoid bool type error
Docs contained an invalid example:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:                                                                                                                   
services.*.restart contains an invalid type, it should be a string 
```

Use quotes to avoid YAML's implicit type conversion.  Someone may also want to do an audit of [other type conversions that might cause problems](https://www.rpatterson.net/blog/docker-gotchas/#yaml-needs-some-zen).