docker-compose documentation version
hochan@hochan-node:~/Desktop/pfc/dockercompose$ sudo docker-compose up --build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the services key, or omit the version key and place your service definitions at the root of the file to use version 1.

Proposed changes
Due to the evolution of version, '3' no longer matches version in docker-compose.

Unreleased project version (optional)
Related issues (optional)