Issue while installation
Issue is :
[root@indretest-0 ~]# yum install docker-ce
Loaded plugins: fastestmirror, langpacks
docker-ce-edge                                                                                                                                   | 2.9 kB  00:00:00
docker-ce-stable                                                                                                                                 | 2.9 kB  00:00:00
Loading mirror speeds from cached hostfile
Package docker-ce-selinux is obsoleted by docker-ce, trying to install docker-ce-17.06.0.ce-1.el7.centos.x86_64 instead
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:17.06.0.ce-1.el7.centos will be installed
--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: container-selinux >= 2.9
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@indretest-0 ~]#

To get rid of this fix as below:
add below as yum repos and install accordingly:
http://mirror.centos.org/centos/7/updates/x86_64/
http://mirror.centos.org/centos/7/extras/x86_64/

then

yum  update  policycoreutils
yum  install policycoreutils-python
yum  install container-selinux
yum install docker-ce