compose 5.0.1 (#23868)
## Description

Note: I can't run `hugo mod vendor`:

```
$ hugo mod vendor 
WARN  deprecated: the ":slugorfilename" permalink token was deprecated in Hugo 0.144.0 and will be removed in a future release. Use ":slugorcontentbasename" instead.
Error: html/template:redirect/single.html:1:13: no such template "_internal/alias.html"
```

## Related issues or tickets

## Reviews

- [ ] Technical review
- [ ] Editorial review
- [ ] Product review

---------

Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>
Co-authored-by: Allie Sadler <102604716+aevesdocker@users.noreply.github.com>