engine/security/rootless: fix reviewdog errors
```
Warning: [vale] reported by reviewdog 🐶
[Docker.Avoid] Consider removing 'very'.

Raw Output:
{"message": "[Docker.Avoid] Consider removing 'very'.", "location": {"path": "content/manuals/engine/security/rootless/_index.md", "range": {"start": {"line": 18, "column": 9}}}, "severity": "WARNING"}
reviewdog: found at least one issue with severity greater than or equal to the given level: warning
Error: [vale] reported by reviewdog 🐶
[Vale.Terms] Use 'cgroup' instead of 'Cgroup'.

Raw Output:
{"message": "[Vale.Terms] Use 'cgroup' instead of 'Cgroup'.", "location": {"path": "content/manuals/engine/security/rootless/troubleshoot.md", "range": {"start": {"line": 73, "column": 3}}}, "severity": "ERROR"}
```

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>